version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - book-network

  book-manager-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-manager-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://postgres:5432/bookdb
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_USERNAME: bookuser
      DATABASE_PASSWORD: bookpass
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    networks:
      - book-network

volumes:
  postgres_data:

networks:
  book-network:
    driver: bridge
